default_stages: [commit]
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-merge-conflict
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.0-alpha.6
    hooks:
      - id: prettier
  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.10.1
    hooks:
      - id: isort
        args: ["--profile", "black", "--filter-files"]
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.3.1
    hooks:
      - id: pyupgrade
        args:
          - --py37-plus
  - repo: https://github.com/ambv/black
    rev: 23.1.0
    hooks:
      - id: black
        language_version: python3.11
  - repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        args:
          - --max-line-length=120
  - repo: https://github.com/nbQA-dev/nbQA
  rev: 0.1.19
  hooks:
    - id: nbqa
      args: ['flake8']
      name: nbqa-flake8
      additional_dependencies: ['flake8']
    - id: nbqa
      args: ['isort', '--nbqa-mutate']
      name: nbqa-isort
      additional_dependencies: ['isort']
    - id: nbqa
      args: ['mypy', '--nbqa-preserve-init']
      name: nbqa-mypy
      additional_dependencies: ['mypy']